services:
  - type: web
    name: ping
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: CHAVE_HOST
        generateValue: true
      - key: NODE_VERSION
        value: "20"
